#!/usr/bin/env python3
"""Build the Ratio site — two pages that share one design system.

  index.src.html      -> index.html      the practitioner front door, written
                                         for fund accountants and operations
                                         leads. Sells outcomes; contains no
                                         Lean, no proofs, no architecture.
  technical.src.html  -> technical.html  the proof-led case, for engineers and
                                         due-diligence reviewers.

The `.src.html` files are what you edit. This script only substitutes
placeholders into a copy of each; it never rewrites a source. Everything gets
inlined, so each page is fully self-contained:

  * `style.css`, the shared design system — held once rather than duplicated
    across both pages, which is also why the fonts are substituted into IT and
    not into the pages
  * the woff2 faces, as `data:` URIs — a font host cannot be relied on (the
    Artifact CSP blocks external subresources outright), and a silent fallback
    would cost the pages half their identity: the serif states claims and
    Outfit carries evidence, and that split IS the type system here
  * the wordmark and the mark, from `marks/` — `wordmark-ratio.svg` is
    generated by `gen_wordmark.py` and committed; `mark-ratio.svg` is drawn

Two output shapes:

  build.py                       -> BODY FRAGMENTS, into ./
                                    What the Artifact host wants: it supplies
                                    <!doctype>, <head> and <body> itself.

  build.py --standalone -d DIR   -> complete HTML documents, for anything that
                                    serves the files directly (GitHub Pages).
                                    Without the wrapper a page renders in
                                    QUIRKS MODE and carries no viewport meta,
                                    so it lays out at 980px on a phone.

  build.py --page index          -> just one of them.

Fonts are resolved in this order, first hit wins:

  $RATIO_SITE_FONTS  ->  ./fonts  ->  /Volumes/Workspace/aion/brand/fonts

./fonts is the vendored copy that makes the build hermetic (and lets it run in
CI). fonts/SOURCES.json carries the sha256 of each face, so drift is detectable;
`--check-fonts` verifies them.

Standard library only. No network. No build-time dependency on fontTools —
that is `gen_wordmark.py`'s problem, and it runs by hand.
"""

import argparse
import base64
import hashlib
import json
import os
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).parent
MARKS = HERE / "marks"

FONTS = {
    "__PLEX7__": "ibm-plex-serif-700-latin.woff2",
    "__PLEX6__": "ibm-plex-serif-600-latin.woff2",
    "__OUTFIT__": "outfit-latin-variable.woff2",
}

MARK_FILES = {
    "__WORDMARK__": "wordmark-ratio.svg",
    "__MARK__": "mark-ratio.svg",
}

# slug -> (source, meta description). The description is only used by
# --standalone; the Artifact host takes its own from the publish call.
PAGES = {
    "index": (
        "index.src.html",
        "Portfolio accounting that ties out every time: exact numbers, a history "
        "you can reproduce on demand, and pricing that does not track your AUM.",
    ),
    "workflows": (
        "workflows.src.html",
        "How fund expertise becomes enforced rules: an expert speaks, a model "
        "drafts, the compiler checks and asks what was left unsaid, a human "
        "approves — walked through on cross-border dividend withholding.",
    ),
    "platform": (
        "platform.src.html",
        "How Ratio is put together: a versioned control plane and a data plane "
        "that only ever runs a pinned configuration, fund rules authored from "
        "expert intent, and a NAV run planned like a query.",
    ),
    "compliance": (
        "compliance.src.html",
        "Audit and examination against Ratio: every figure names the rules that "
        "produced it, every rule change is a signed commit, and any prior period "
        "re-runs exactly — so the answer is a query, not a project.",
    ),
    "roadmap": (
        "roadmap.src.html",
        "Ratio's route to capability parity with the incumbent wealth-technology "
        "stack, component by component.",
    ),
    "team": (
        "team.src.html",
        "The people behind Ratio, and the fund-accounting experience it is "
        "built on.",
    ),
    "technical": (
        "technical.src.html",
        "How Ratio works: an accounting kernel whose central invariant is "
        "machine-checked in Lean 4, and whose running engine is generated from "
        "those proofs.",
    ),
}

# Nav order is deliberate and is NOT sorted(PAGES) — it runs from audience to
# mechanism: what it does, how it is built, when it lands, why it is correct.
NAV_ORDER = ["index", "workflows", "platform", "compliance", "roadmap", "technical", "team"]

TITLE_RE = re.compile(r"[ \t]*<title>(.*?)</title>\n?", re.S)

FALLBACK_FONT_DIR = pathlib.Path("/Volumes/Workspace/aion/brand/fonts")


def font_dir() -> pathlib.Path:
    """First directory holding every face we need."""
    candidates = []
    if os.environ.get("RATIO_SITE_FONTS"):
        candidates.append(pathlib.Path(os.environ["RATIO_SITE_FONTS"]))
    candidates.append(HERE / "fonts")
    candidates.append(FALLBACK_FONT_DIR)
    for c in candidates:
        if all((c / name).is_file() for name in FONTS.values()):
            return c
    sys.exit(
        "no directory holds all of "
        + ", ".join(sorted(FONTS.values()))
        + "\ntried: "
        + ", ".join(str(c) for c in candidates)
    )


def check_fonts(fonts: pathlib.Path) -> None:
    """Verify each vendored face against fonts/SOURCES.json."""
    manifest = HERE / "fonts" / "SOURCES.json"
    if not manifest.is_file():
        sys.exit(f"missing {manifest}")
    bad = []
    for entry in json.loads(manifest.read_text()):
        path = fonts / entry["file"]
        if not path.is_file():
            bad.append(f"{entry['file']}: absent")
            continue
        got = hashlib.sha256(path.read_bytes()).hexdigest()
        if got != entry["sha256"]:
            bad.append(f"{entry['file']}: {got} != {entry['sha256']}")
    if bad:
        sys.exit("font digest mismatch:\n  " + "\n  ".join(bad))
    print(f"fonts OK ({len(FONTS)} faces verified against SOURCES.json)")


def strip_svg_comments(svg: str) -> str:
    """Drop the design rationale from the shipped markup.

    The comments in marks/*.svg explain why the mark is shaped the way it is;
    that belongs in the repository, not in every byte served to every reader.
    """
    return re.sub(r"<!--.*?-->\s*", "", svg, flags=re.S)


def substitute(html: str, token: str, payload: str) -> str:
    """Replace `token`, insisting it occurs exactly once.

    Exactly-once is the point, not defensiveness. `str.replace` hits every
    occurrence, so a token named in the source's own documentation gets a full
    font or a whole SVG inlined into that comment — which is silent, since a
    comment renders as nothing, and merely doubles the page weight. This build
    shipped 226 KB that way before the check existed.
    """
    n = html.count(token)
    if n != 1:
        sys.exit(
            f"placeholder {token} occurs {n} times in site.src.html, expected exactly 1"
            + (" — is it named in a comment?" if n > 1 else "")
        )
    return html.replace(token, payload)


def script_block() -> str:
    """nav.js, inlined. One source of truth rather than a copy per page."""
    return "<script>\n" + (HERE / "nav.js").read_text().strip() + "\n</script>"


def stylesheet(fonts: pathlib.Path) -> str:
    """style.css with the three faces inlined, wrapped ready to drop into a page."""
    css = (HERE / "style.css").read_text()
    for token, name in FONTS.items():
        payload = base64.b64encode((fonts / name).read_bytes()).decode("ascii")
        css = substitute(css, token, payload)
    return "<style>\n" + css.strip() + "\n</style>"


PHOTOS = HERE / "photos"
PHOTO_MIME = {".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".png": "image/png",
              ".webp": "image/webp"}


def inline_photos(html: str) -> str:
    """Swap an initials monogram for a real headshot when one has been supplied.

    Team cards carry `<div class="r-avatar" data-photo="slug">XY</div>`. If
    `photos/<slug>.<ext>` exists it is inlined as a data: URI and replaces the
    initials; otherwise the monogram stands. Inlining is not optional — an
    external image URL is blocked by the Artifact CSP and fails verify.py.
    """
    def swap(m: re.Match) -> str:
        head, slug, _initials = m.group(0), m.group(1), m.group(2)
        for ext, mime in PHOTO_MIME.items():
            f = PHOTOS / f"{slug}{ext}"
            if f.is_file():
                b64 = base64.b64encode(f.read_bytes()).decode("ascii")
                return (head[: head.index(">") + 1]
                        + f'<img src="data:{mime};base64,{b64}" alt=""></div>')
        # No photo: fall back to the engraved monogram rather than bare
        # initials, so a card without a portrait still looks intentional.
        mark = MARKS / f"avatar-{slug}.svg"
        if mark.is_file():
            return (head[: head.index(">") + 1]
                    + strip_svg_comments(mark.read_text()).strip() + "</div>")
        return head

    return re.sub(r'<div class="r-avatar" data-photo="([a-z-]+)">([^<]*)</div>',
                  swap, html)


def render(src: pathlib.Path, css_block: str, links: dict[str, str]) -> str:
    html = src.read_text()
    html = inline_photos(html)
    html = substitute(html, "__STYLE__", css_block)
    html = substitute(html, "__SCRIPT__", script_block())
    for token, name in MARK_FILES.items():
        svg = strip_svg_comments((MARKS / name).read_text()).strip()
        html = substitute(html, token, svg)
    # The two pages link to each other by relative filename, which is right for
    # a directory of files and wrong for the Artifact host, where each page gets
    # its own opaque URL and `technical.html` resolves to nothing. --link swaps
    # in absolute URLs at publish time without the sources having to know.
    for slug, url in links.items():
        html = html.replace(f'href="{slug}.html"', f'href="{url}"')
    return html


def standalone(fragment: str, description: str) -> str:
    """Wrap the fragment in a real document, hoisting its <title> into <head>."""
    m = TITLE_RE.search(fragment)
    title = m.group(1).strip() if m else "Ratio"
    body = TITLE_RE.sub("", fragment, count=1) if m else fragment
    return (
        "<!doctype html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        '<meta name="color-scheme" content="light dark">\n'
        f"<title>{title}</title>\n"
        f'<meta name="description" content="{description}">\n'
        "</head>\n"
        "<body>\n"
        f"{body.lstrip()}"
        "\n</body>\n"
        "</html>\n"
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "-d", "--out-dir", default=str(HERE),
        help="output directory (default: alongside the sources)",
    )
    ap.add_argument(
        "--page", choices=sorted(PAGES), action="append",
        help="build only this page (repeatable; default: all)",
    )
    ap.add_argument(
        "--standalone", action="store_true",
        help="emit complete HTML documents instead of body fragments",
    )
    ap.add_argument(
        "--check-fonts", action="store_true",
        help="verify vendored faces against fonts/SOURCES.json, then build",
    )
    ap.add_argument(
        "--link", action="append", metavar="SLUG=URL", default=[],
        help="rewrite the cross-link to SLUG as an absolute URL "
             "(e.g. --link technical=https://…); repeatable. For hosts where "
             "the pages do not sit in one directory.",
    )
    args = ap.parse_args()

    links = {}
    for pair in args.link:
        slug, _, url = pair.partition("=")
        if slug not in PAGES or not url:
            sys.exit(f"--link expects SLUG=URL with SLUG in {sorted(PAGES)}, got {pair!r}")
        links[slug] = url

    fonts = font_dir()
    if args.check_fonts:
        check_fonts(fonts)

    css_block = stylesheet(fonts)
    out_dir = pathlib.Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    shape = "document" if args.standalone else "fragment"

    for slug in args.page or sorted(PAGES):
        src_name, description = PAGES[slug]
        html = render(HERE / src_name, css_block, links)
        if args.standalone:
            html = standalone(html, description)
        out = out_dir / f"{slug}.html"
        out.write_text(html)
        print(f"{out}  {out.stat().st_size / 1024:.0f} KB  ({shape})")

    print(f"fonts from {fonts}")


if __name__ == "__main__":
    main()
