[package]
name = "ratio-console"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
ratio-chart = { path = "../ratio-chart" }
ratio-nav = { path = "../ratio-nav" }
ratio-rules = { path = "../ratio-rules" }
ratio-store = { path = "../ratio-store" }
anyhow = "1"
prost = "0.13"
