#!/usr/bin/env python3
"""Wrap the built console HTML in a Rust raw string literal."""

import pathlib
import sys

html = pathlib.Path(sys.argv[1]).read_text()

# A raw string needs a delimiter the content does not contain. The console DOES
# contain `"#` — `href="#"` — so a naive r#"…"# ends the literal early and
# produces a compile error nobody would connect to an anchor tag.
hashes = 1
while '"' + "#" * hashes in html:
    hashes += 1
h = "#" * hashes

pathlib.Path(sys.argv[2]).write_text(
    "// Generated by //web:console_rs. Do not edit.\n"
    f"pub const CONSOLE: &str = r{h}\"{html}\"{h};\n"
)
